### PR TITLE
Add GitHub action to publish release on PyPI

### PR DESCRIPTION
**Pull request by teutoburg**
This is very experimental and will likely be modified soon, but needs to be merged in to be tested.

### CODE REVIEW

**Comment by hugobuddel** [comment]
Does it work? There are packages on PyPI so seems like it does? I hope we can copy this to all the other projects once you're happy with it

**Comment by teutoburg** [comment]
It did indeed work first try! I'm currently in the process of refining it a bit (and another workflow). Once it's done, my plan was to move it to DevOps. Using this repo as a testbed, because so far nothing depends on it, so can't break anything.

**Comment by teutoburg** [comment]
Oh and for this to work it would be necessary to switch our other pyproject.toml files to use Poetry, which does the building and packaging here. It would be possible to do such a workflow without Poetry, but it also has other advantages, which I'll explore in this repo as well.

**Comment by hugobuddel** [comment]
I think it would be fine to move the other packages to poetry as well. I couldn't decide between all the different packaging tools, so poetry is fine.

The state at the beginning of this year: "[How to improve Python packaging, or why fourteen tools are at least twelve too many](https://chriswarrick.com/blog/2023/01/15/how-to-improve-python-packaging/)"

**Pull request merged**
